package by.training.wish;

import by.training.dao.ConnectionManager;
import by.training.dao.DaoException;
import org.junit.*;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.mockito.Mockito;

import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

@RunWith(JUnit4.class)
public class WishDaoTest {
    private static Connection connection;
    private WishDao wishDao;

    @BeforeClass
    public static void initConnection() throws SQLException {
        connection =
                DriverManager.getConnection("jdbc:hsqldb:mem:restaurant_db", "test", "test");
    }

    @AfterClass
    public static void closeConnection() throws SQLException {
        connection.close();
    }

    @Before
    public void createTable() throws SQLException {
        ConnectionManager mockConnectionManager = Mockito.mock(ConnectionManager.class);
        wishDao = new WishDaoImpl(mockConnectionManager);
        Mockito.when(mockConnectionManager.getConnection()).thenReturn(createConnectionProxy(connection));
        String createTable = "CREATE TABLE order_wish (\n" +
                "  wish_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,\n" +
                "  wish varchar(150) NOT NULL,\n" +
                "  food_order_id BIGINT NOT NULL,\n" +
                ")";
        executeSql(createTable);

        String insertWish1 = "insert into order_wish(wish, food_order_id) values('more food', 10)";
        executeSql(insertWish1);

        String insertWish2 = "insert into order_wish(wish, food_order_id) values('smth interesting', 15)";
        executeSql(insertWish2);

        String insertWish3 = "insert into order_wish(wish, food_order_id) values('more light', 10)";
        executeSql(insertWish3);

        String insertWish4 = "insert into order_wish(wish, food_order_id) values('baby chair', 10)";
        executeSql(insertWish4);

    }

    @Test
    public void shouldInsert() throws DaoException {
        List<WishDto> beforeInsert = wishDao.findAll();
        WishDto wishDto = WishDto.builder()
                .wish("More water")
                .foodOrderId(98)
                .build();
        wishDao.save(wishDto);
        List<WishDto> afterInsert = wishDao.findAll();
        Assert.assertEquals(1, afterInsert.size() - beforeInsert.size());
    }

    @Test
    public void shouldRemove() throws DaoException {
        List<WishDto> beforeRemove = wishDao.findAll();
        wishDao.delete(2L);
        List<WishDto> afterRemove = wishDao.findAll();
        Assert.assertEquals(1, beforeRemove.size() - afterRemove.size());
    }

    @Test
    public void shouldFindAllOrderWishes() throws WishDaoException {
        List<WishDto> orderWish = wishDao.findOrderWishes(10L);
        Assert.assertEquals(3, orderWish.size());
    }

    @Test
    public void shouldGetById() throws DaoException {
        WishDto wishDto = wishDao.getById(3L);
        Assert.assertNotNull(wishDto);
    }

    @Test(expected = WishDaoException.class)
    public void shouldThrowExceptionAfterGetById() throws DaoException {
        WishDto wishDto = wishDao.getById(100L);
        Assert.fail("Should throw exception cause wrong id");
    }

    private void executeSql(String sql) throws SQLException {
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.executeUpdate();
        statement.close();
    }

    private Connection createConnectionProxy(Connection realConnection) {
        return (Connection) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{Connection.class},
                (proxy, method, args) -> {
                    if (method.getName().equals("close")) {
                        return null;
                    } else {
                        return method.invoke(realConnection, args);
                    }
                });
    }

    @After
    public void dropTable() throws SQLException {
        String sql = "drop table order_wish";
        executeSql(sql);
    }
}
