-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 12:43:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurant_db` ;

-- -----------------------------------------------------
-- Table `restaurant_db`.`user_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`user_discount` (
  `discount_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `discount_amount` DECIMAL(10,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`discount_id`),
  UNIQUE INDEX `discount_id_UNIQUE` (`discount_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`user_account` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_locked` TINYINT NOT NULL DEFAULT '0',
  `discount_id` BIGINT(20) NULL DEFAULT NULL,
  `user_avatar` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_account_user_discount1_idx` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_user_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `restaurant_db`.`user_discount` (`discount_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`food_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`food_order` (
  `order_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_date` TIMESTAMP NOT NULL,
  `booking_date` VARCHAR(45) NOT NULL,
  `order_status` VARCHAR(45) NOT NULL DEFAULT 'Processing',
  `customer_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_food_order_user_account1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_order_user_account1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `restaurant_db`.`user_account` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`ordered_dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`ordered_dish` (
  `dish_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dish_name` VARCHAR(45) NOT NULL,
  `dish_price` DECIMAL(10,0) NOT NULL,
  `dish_photo` LONGBLOB NOT NULL,
  `dish_description` VARCHAR(1500) NULL DEFAULT NULL,
  PRIMARY KEY (`dish_id`),
  UNIQUE INDEX `dish_id_UNIQUE` (`dish_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`food_order_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`food_order_relation` (
  `order_id` BIGINT(20) NOT NULL,
  `dish_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`order_id`, `dish_id`),
  INDEX `fk_food_order_has_ordered_dish_ordered_dish1_idx` (`dish_id` ASC) VISIBLE,
  INDEX `fk_food_order_has_ordered_dish_food_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_order_has_ordered_dish_food_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `restaurant_db`.`food_order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_food_order_has_ordered_dish_ordered_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `restaurant_db`.`ordered_dish` (`dish_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`order_wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`order_wish` (
  `wish_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `wish` VARCHAR(500) NOT NULL,
  `food_order_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`wish_id`),
  UNIQUE INDEX `wish_id_UNIQUE` (`wish_id` ASC) VISIBLE,
  INDEX `fk_order_wish_food_order1_idx` (`food_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_wish_food_order1`
    FOREIGN KEY (`food_order_id`)
    REFERENCES `restaurant_db`.`food_order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`user_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`user_contact` (
  `contact_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`contact_id`),
  UNIQUE INDEX `contact_id_UNIQUE` (`contact_id` ASC) VISIBLE,
  INDEX `fk_user_contact_user_account1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_contact_user_account1`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurant_db`.`user_account` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`user_role` (
  `role_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `default_role` TINYINT(3) UNSIGNED NULL DEFAULT '1',
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`user_role_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`user_role_relation` (
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  INDEX `fk_user_account_has_user_role_user_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_account_has_user_role_user_account1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_has_user_role_user_account1`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurant_db`.`user_account` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_account_has_user_role_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `restaurant_db`.`user_role` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`user_wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`user_wallet` (
  `wallet_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `wallet_name` VARCHAR(45) NOT NULL DEFAULT 'Main wallet',
  `wallet_amount` DECIMAL(10,0) NOT NULL DEFAULT '0',
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`wallet_id`),
  UNIQUE INDEX `wallet_id_UNIQUE` (`wallet_id` ASC) VISIBLE,
  INDEX `fk_user_wallet_user_account1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_wallet_user_account1`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurant_db`.`user_account` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_db`.`booked_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_db`.`booked_table` (
  `table_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `capacity` INT(11) NOT NULL,
  PRIMARY KEY (`table_id`),
  UNIQUE INDEX `table_id_UNIQUE` (`table_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
