package by.training.dish;

import by.training.dao.ConnectionManager;
import by.training.dao.DaoException;
import org.junit.*;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.mockito.Mockito;

import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

@RunWith(JUnit4.class)
public class DishDaoTest {
    private static Connection connection;
    private DishDao dishDao;

    @BeforeClass
    public static void initConnection() throws SQLException {
        connection =
                DriverManager.getConnection("jdbc:hsqldb:mem:restaurant_db", "test", "test");
    }

    @AfterClass
    public static void closeConnection() throws SQLException {
        connection.close();
    }

    @Before
    public void createTable() throws SQLException {
        ConnectionManager mockConnectionManager = Mockito.mock(ConnectionManager.class);
        dishDao = new DishDaoImpl(mockConnectionManager);
        Mockito.when(mockConnectionManager.getConnection()).thenReturn(createConnectionProxy(connection));
        String createTable = "CREATE TABLE ordered_dish (\n" +
                "  dish_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,\n" +
                "  dish_name varchar(150) NOT NULL,\n" +
                "  dish_photo varchar(150),\n" +
                "  dish_description varchar(150),\n" +
                "  dish_price BIGINT NOT NULL,\n" +
                ")";
        executeSql(createTable);

        String insertDish1 = "insert into ordered_dish (dish_name, dish_price) values('milk', 15)";
        executeSql(insertDish1);

        String insertDish2 = "insert into ordered_dish (dish_name, dish_price) values('meat', 45)";
        executeSql(insertDish2);

        String insertDish3 = "insert into ordered_dish (dish_name, dish_price) values('cheese', 115)";
        executeSql(insertDish3);

        String insertDish4 = "insert into ordered_dish (dish_name, dish_price) values('potato', 99)";
        executeSql(insertDish4);

        String insertDish5 = "insert into ordered_dish (dish_name, dish_price) values('cherry', 21)";
        executeSql(insertDish5);
    }

    @Test
    public void shouldInsert() throws DaoException {
        List<DishDto> beforeInsert = dishDao.findAll();
        DishDto dishDto = DishDto.builder()
                .name("Blue chees")
                .price(189)
                .build();
        dishDao.save(dishDto);
        List<DishDto> afterInsert = dishDao.findAll();
        Assert.assertEquals(1, afterInsert.size() - beforeInsert.size());
    }

    @Test
    public void shouldRemove() throws DaoException {
        List<DishDto> beforeRemove = dishDao.findAll();
        dishDao.delete(2L);
        List<DishDto> afterRemove = dishDao.findAll();
        Assert.assertEquals(1, beforeRemove.size() - afterRemove.size());
    }

    @Test
    public void shouldGetById() throws DaoException {
        DishDto dishDto = dishDao.getById(3L);
        Assert.assertNotNull(dishDto);
    }

    @Test(expected = DishDaoException.class)
    public void shouldThrowExceptionAfterGetById() throws DaoException {
        DishDto dishDto = dishDao.getById(100L);
        Assert.fail("Should throw exception cause wrong id");
    }

    private void executeSql(String sql) throws SQLException {
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.executeUpdate();
        statement.close();
    }

    private Connection createConnectionProxy(Connection realConnection) {
        return (Connection) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{Connection.class},
                (proxy, method, args) -> {
                    if (method.getName().equals("close")) {
                        return null;
                    } else {
                        return method.invoke(realConnection, args);
                    }
                });
    }

    @After
    public void dropTable() throws SQLException {
        String sql = "drop table ordered_dish";
        executeSql(sql);
    }
}
