package by.training.wallet;

import by.training.dao.ConnectionManager;
import by.training.dao.DaoException;
import org.junit.*;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.mockito.Mockito;

import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

@RunWith(JUnit4.class)
public class WalletDaoTest {
    private static Connection connection;
    private WalletDao walletDao;

    @BeforeClass
    public static void initConnection() throws SQLException {
        connection =
                DriverManager.getConnection("jdbc:hsqldb:mem:restaurant_db", "test", "test");
    }

    @AfterClass
    public static void closeConnection() throws SQLException {
        connection.close();
    }

    @Before
    public void createTable() throws SQLException {
        ConnectionManager mockConnectionManager = Mockito.mock(ConnectionManager.class);
        walletDao = new WalletDaoImpl(mockConnectionManager);
        Mockito.when(mockConnectionManager.getConnection()).thenReturn(createConnectionProxy(connection));
        String createTable = "CREATE TABLE user_wallet (\n" +
                "  wallet_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,\n" +
                "  wallet_name varchar(150) NOT NULL,\n" +
                "  wallet_amount DECIMAL,\n" +
                "  user_id BIGINT NOT NULL,\n" +
                ")";
        executeSql(createTable);

        String insertWallet1 = "insert into user_wallet (wallet_amount, wallet_name, user_id) values(100, 'main', 1)";
        executeSql(insertWallet1);

        String insertWallet2 = "insert into user_wallet (wallet_amount, wallet_name, user_id) values(10140, 'qiq', 51)";
        executeSql(insertWallet2);

        String insertWallet3 = "insert into user_wallet (wallet_amount, wallet_name, user_id) values(90, 'qiwi', 1)";
        executeSql(insertWallet3);

        String insertWallet4 = "insert into user_wallet (wallet_amount, wallet_name, user_id) values(289, 'my', 14)";
        executeSql(insertWallet4);
    }

    @Test
    public void shouldInsert() throws DaoException {
        List<WalletDto> beforeInsert = walletDao.findAll();
        WalletDto walletDto = WalletDto.builder()
                .name("Debet")
                .userId(10)
                .build();
        walletDao.save(walletDto);
        List<WalletDto> afterInsert = walletDao.findAll();
        Assert.assertEquals(1, afterInsert.size() - beforeInsert.size());
    }

    @Test
    public void shouldRemove() throws DaoException {
        List<WalletDto> beforeRemove = walletDao.findAll();
        walletDao.delete(2L);
        List<WalletDto> afterRemove = walletDao.findAll();
        Assert.assertEquals(1, beforeRemove.size() - afterRemove.size());
    }

    @Test
    public void shouldFindAllUserWallets() throws DaoException {
        List<WalletDto> userWallets = walletDao.findUserWallets(1L);
        Assert.assertEquals(2, userWallets.size());
    }

    private void executeSql(String sql) throws SQLException {
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.executeUpdate();
        statement.close();
    }

    private Connection createConnectionProxy(Connection realConnection) {
        return (Connection) Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{Connection.class},
                (proxy, method, args) -> {
                    if (method.getName().equals("close")) {
                        return null;
                    } else {
                        return method.invoke(realConnection, args);
                    }
                });
    }

    @After
    public void dropTable() throws SQLException {
        String sql = "drop table user_wallet";
        executeSql(sql);
    }
}
